---
x-volumes: &volumes
  - 'src_data:/opt/src'
  - 'exercism_data:/home/coder/exercism'
  - 'home_config_data:/home/coder/.config'
  - 'home_cache_data:/home/coder/.cache'
  - 'home_share_data:/home/coder/.local/share'
  - 'home_state_data:/home/coder/.local/state'
  - 'gopath_data:/home/coder/.local/share/go'
  - './config/code-server:/home/coder/.config/code-server'
  - './config/mise:/home/coder/.config/mise'
  - './config/nvim/lua/custom:/home/coder/.config/nvim/lua/custom'
  - './config/starship:/home/coder/.config/starship'
  - './config/tmux:/home/coder/.config/tmux'
  - './config/tmuxp:/home/coder/.config/tmuxp'

services:
  coder:
    image: 'joaodubas/code-server:4.20.1'
    build:
      context: .
      target: code-server
    init: true
    hostname: coder
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PASSWORD: '${CODER_PASSWORD:-password}'
      SERVICE_URL: 'https://open-vsx.org/vscode/gallery'
      ITEM_URL: 'https://open-vsx.org/vscode/item'
    volumes: *volumes

volumes:
  src_data: {}
  gopath_data: {}
  exercism_data: {}
  home_config_data: {}
  home_cache_data: {}
  home_share_data: {}
  home_state_data: {}
