---
version: '3.7'
services:
  coder:
    image: 'joaodubas/code-server:4.0.0'
    build:
      context: .
    init: true
    hostname: coder
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PASSWORD: '${CODER_PASSWORD:-password}'
      SERVICE_URL: 'https://open-vsx.org/vscode/gallery'
      ITEM_URL: 'https://open-vsx.org/vscode/item'
    volumes:
      - 'src_data:/opt/src'
      - 'gopath_data:/go'
      - 'exercism_data:/home/coder/exercism'
      - 'config_data:/home/coder/.config'
      - 'cache_data:/home/coder/.cache'
      - './config/nvim:/home/coder/.config/nvim'
      - './config/zsh:/home/coder/.config/zsh'
      - './config/code-server:/home/coder/.config/code-server'
volumes:
  src_data: {}
  gopath_data: {}
  exercism_data: {}
  config_data: {}
  cache_data: {}
