---
version: '3.7'
services:
  coder:
    image: 'joaodubas/code-server:3.6.0-zsh'
    build:
      context: .
    init: true
    hostname: coder
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - '/mnt/volume_docker/docker:/var/lib/docker'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker-compose:/usr/bin/docker-compose'
      - './config/nvim:/root/.config/nvim'
      - 'src_data:/opt/src'
      - 'gopath_data:/go'
      - 'exercism_config_data:/root/.config/exercism'
    working_dir: /opt/src
    command: '--user-data-dir /opt/src --bind-addr 0.0.0.0:8443 --auth password'
volumes:
  src_data: {}
  gopath_data: {}
  exercism_config_data: {}
networks:
  default:
    external:
      name: proxy_upstream
