---
x-volumes: &volumes
  - 'src_data:/opt/src'
  - 'exercism_data:/home/coder/exercism'
  - 'home_config_data:/home/coder/.config'
  - 'home_cache_data:/home/coder/.cache'
  - 'home_share_data:/home/coder/.local/share'
  - 'gopath_data:/home/coder/.local/share/go'
  - 'pyenv_versions_data:/home/coder/.local/src/pyenv/versions'
  - './config/code-server:/home/coder/.config/code-server'
  - './config/nvim:/home/coder/.config/nvim'
  - './config/starship:/home/coder/.config/starship'
  - './config/zsh:/home/coder/.config/zsh'

services:
  coder:
    image: 'joaodubas/code-server:4.9.1'
    build:
      context: .
      target: code-server
    init: true
    hostname: coder
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PASSWORD: '${CODER_PASSWORD:-password}'
      SERVICE_URL: 'https://open-vsx.org/vscode/gallery'
      ITEM_URL: 'https://open-vsx.org/vscode/item'
    volumes: *volumes
  openvscode:
    image: 'joaodubas/openvscode-server:1.74.3'
    build:
      context: .
      target: openvscode-server
    init: true
    hostname: openvscode
    restart: unless-stopped
    volumes: *volumes

volumes:
  src_data: {}
  gopath_data: {}
  exercism_data: {}
  home_config_data: {}
  home_cache_data: {}
  home_share_data: {}
  pyenv_versions_data: {}
