---
version: '3.4'
services:
  coder:
    image: 'joaodubas/code-server:preview'
    build:
      context: .
    hostname: coder
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PASSWORD: Ozw3MSWwN2OCueyjzw9mWj6r9jBgPs9R
    volumes:
      - '/var/lib/docker:/var/lib/docker'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker-compose:/usr/bin/docker-compose'
      - 'src_data:/opt/src'
    working_dir: /opt/src
    command: --user-data-dir /opt/src --port 8443 --auth password
volumes:
  src_data: {}
networks:
  default:
    external:
      name: proxy_upstream
