---
version: '3.7'
services:
  coder:
    image: 'joaodubas/code-server:3.9.3-zsh'
    build:
      context: .
    init: true
    hostname: coder
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - './config/nvim:/home/coder/.config/nvim'
      - './config/zsh:/home/coder/.config/zsh'
      - 'src_data:/opt/src'
      - 'gopath_data:/go'
      - 'exercism_config_data:/home/coder/.config/exercism'
      - 'zsh_cache_data:/home/coder/.cache/zsh'
    working_dir: /opt/src
    command: '--user-data-dir /opt/src --bind-addr 0.0.0.0:8443 --auth password'
volumes:
  src_data: {}
  gopath_data: {}
  exercism_config_data: {}
  zsh_cache_data: {}
networks:
  default:
    external:
      name: proxy_upstream
