---
version: '3.7'

x-volumes: &volumes
  - 'src_data:/opt/src'
  - 'exercism_data:/home/coder/exercism'
  - 'nvim_config_data:/home/coder/.config'
  - 'nvim_cache_data:/home/coder/.cache'
  - 'nvim_share_data:/home/coder/.local/share'
  - 'gopath_data:/home/coder/.local/share/go'
  - 'pyenv_versions_data:/home/coder/.local/src/pyenv/versions'
  - './config/nvim:/home/coder/.config/nvim'
  - './config/zsh:/home/coder/.config/zsh'
  - './config/code-server:/home/coder/.config/code-server'

services:
  coder:
    image: 'joaodubas/code-server:4.4.0'
    build:
      context: .
      target: code-server
    init: true
    hostname: coder
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PASSWORD: '${CODER_PASSWORD:-password}'
      SERVICE_URL: 'https://open-vsx.org/vscode/gallery'
      ITEM_URL: 'https://open-vsx.org/vscode/item'
    volumes: *volumes
  openvscode:
    image: 'joaodubas/openvscode-server:1.67.0'
    build:
      context: .
      target: openvscode-server
    init: true
    hostname: openvscode
    restart: unless-stopped
    volumes: *volumes

volumes:
  src_data: {}
  gopath_data: {}
  exercism_data: {}
  nvim_config_data: {}
  nvim_cache_data: {}
  nvim_share_data: {}
  pyenv_versions_data: {}
