[tools]
awscli = "2.15.49"
bat = "0.24.0"
bitwarden = "2024.4.1"
circleci-cli = "0.1.30549"
ctlptl = "0.8.29"
dagger = "0.11.4"
eksctl = "0.180.0"
elixir = "1.17.0-otp-27"
erlang = "27.0"
eza = "0.18.15"
fzf = "0.52.1"
go = "1.22.3"
helm = "3.14.4"
k3d = "5.6.3"
k3sup = "0.13.5"
k9s = "0.32.4"
kind = "0.22.0"
kubectl = "1.30.0"
kubie = "0.23.0"
lefthook = "1.6.11"
lua = "5.4.6"
luajit = "2.0.5--2.4.4"
node = "22.1.0"
poetry = "1.8.3"
python = "3.12.3"
r = "4.4.0"
ripgrep = "14.1.0"
rust = "1.78.0"
starship = "1.18.2"
task = "3.37.2"
terraform = "1.8.3"
tilt = "0.33.13"
tmux = "3.4"
usage = "0.3.0"
usql = "0.19.1"
yarn = "1.22.19"
zoxide = "0.9.4"

[settings]
experimental = true
python_compile = true
