---
version: '3'
services:
  broker:
    image: 'rabbitmq:3.7.4-management'
  result:
    image: 'redis:4.0.9'
  metric:
    image: 'influxdb:1.5.2'
  app:
    image: async-app
    build: .
    volumes:
      - './svc:/app/svc'
    command: pipenv run celery worker -A svc -l info -n async-01 --heartbeat-interval 30
