---
version: '3'
services:
  broker:
    image: 'rabbitmq:3.7.4-management'
  result:
    image: 'redis:4.0.9'
  metric:
    image: 'influxdb:1.5.2'
  dash:
    image: 'grafana/grafana:5.1.2'
    ports:
      - '3000:3000'
  app:
    image: async-app
    build: .
    volumes:
      - './svc:/app/svc'
    command: poetry run celery worker -A svc -l info -E --heartbeat-interval 30
