---
- hosts: dev
  vars:
    version:
      erlang: '23.2.4'
      elixir: '1.11.3-otp-23'
      golang: '1.15.8'
      java: 'openjdk-16'
      kotlin: '1.4.30'
      nodejs: '15.8.0'
      yarn: '1.22.10'
  # NOTE (jpd): install jq before installing asdf
  roles:
    - role: cimon-io.asdf
      asdf_version: 'v0.8.0'
      asdf_user: '{{ ansible_env.USER }}'
      asdf_user_home: '{{ ansible_env.HOME }}'
      asdf_plugins:
        - name: 'java'
          versions: ['{{ version.java }}']
          global: '{{ version.java }}'
        - name: 'kotlin'
          versions: ['{{ version.kotlin }}']
          global: '{{ version.kotlin }}'
        - name: 'erlang'
          versions: ['{{ version.erlang }}']
          global: '{{ version.erlang }}'
        - name: 'elixir'
          versions: ['{{ version.elixir }}']
          global: '{{ version.elixir }}'
        - name: 'golang'
          versions: ['{{ version.golang }}']
          global: '{{ version.golang }}'
        - name: 'nodejs'
          versions: ['{{ version.nodejs }}']
          global: '{{ version.nodejs }}'
        - name: 'yarn'
          versions: ['{{ version.yarn }}']
          global: '{{ version.yarn }}'
