---
- hosts: dev
  vars:
    version:
      erlang: '22.3.3'
      elixir: '1.10.3-otp-22'
      golang: '1.14.2'
      java: 'adopt-openjdk-14.0.1+7_openj9-0.20.0'
      kotlin: '1.3.72'
      nodejs: '14.2.0'
      yarn: '1.22.4'
  # NOTE (jpd): install jq before installing asdf
  roles:
    - role: cimon-io.asdf
      asdf_version: 'v0.7.4'
      asdf_user: '{{ ansible_env.USER }}'
      asdf_user_home: '{{ ansible_env.HOME }}'
      asdf_plugins:
        - name: 'java'
          versions: ['{{ version.java }}']
          global: '{{ version.java }}'
        - name: 'kotlin'
          versions: ['{{ version.kotlin }}']
          global: '{{ version.kotlin }}'
        - name: 'erlang'
          versions: ['{{ version.erlang }}']
          global: '{{ version.erlang }}'
        - name: 'elixir'
          versions: ['{{ version.elixir }}']
          global: '{{ version.elixir }}'
        - name: 'golang'
          versions: ['{{ version.golang }}']
          global: '{{ version.golang }}'
        - name: 'nodejs'
          versions: ['{{ version.nodejs }}']
          global: '{{ version.nodejs }}'
        - name: 'yarn'
          versions: ['{{ version.yarn }}']
          global: '{{ version.yarn }}'
