---
- hosts: dev
  vars:
    version:
      erlang: '22.0.7'
      elixir: '1.9.1-otp-22'
      golang: '1.13'
      java: 'adopt-openjdk-13+33_openj9-0.16.0'
      kotlin: '1.3.50'
      nodejs: '12.10.0'
      yarn: '1.18.0'
  tasks:
    # NOTE (jpd): list all java versions depends on jq
    - name: install jq
      become: yes
      apt:
        name: jq
        state: present
        update_cache: yes
  roles:
    - role: cimon-io.asdf
      asdf_version: 'v0.7.4'
      asdf_user: '{{ ansible_env.USER }}'
      asdf_user_home: '{{ ansible_env.HOME }}'
      asdf_plugins:
        - name: 'java'
          versions: ['{{ version.java }}']
          global: '{{ version.java }}'
        - name: 'kotlin'
          versions: ['{{ version.kotlin }}']
          global: '{{ version.kotlin }}'
        - name: 'erlang'
          versions: ['{{ version.erlang }}']
          global: '{{ version.erlang }}'
        - name: 'elixir'
          versions: ['{{ version.elixir }}']
          global: '{{ version.elixir }}'
        - name: 'golang'
          versions: ['{{ version.golang }}']
          global: '{{ version.golang }}'
        - name: 'nodejs'
          versions: ['{{ version.nodejs }}']
          global: '{{ version.nodejs }}'
        - name: 'yarn'
          versions: ['{{ version.yarn }}']
          global: '{{ version.yarn }}'
