---
- hosts: dev
  vars:
    ripgrep:
      version: '13.0.0'
      destination: '/tmp/ripgrep.deb'
  tasks:
    - name: check ripgrep deb already installed
      become: yes
      command: dpkg-query -W ripgrep
      register: ripgrep_check_deb
      failed_when: ripgrep_check_deb.rc > 1
      changed_when: ripgrep_check_deb.rc == 1
    - name: download ripgrep deb
      get_url:
        url: 'https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep.version }}/ripgrep_{{ ripgrep.version }}_amd64.deb'
        dest: '{{ ripgrep.destination }}'
      when: ripgrep_check_deb.rc == 1
    - name: install ripgrep deb
      become: yes
      apt:
        deb: '{{ ripgrep.destination }}'
      when: ripgrep_check_deb.rc == 1
    - name: remove ripgrep deb
      file:
        path: '{{ ripgrep.destination }}'
        state: absent
