---
- name: system updates
  hosts: dev
  become: yes
  tasks:
    - name: update sysctl configuration
      sysctl:
        name: "{{item.name}}"
        value: "{{item.value}}"
      loop:
        # needed to run elastic search:
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
        - name: vm.max_map_count
          value: 262144
