---
- name: system updates
  hosts: dev
  become: yes
  tasks:
    - name: update sysctl configuration
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        # needed to run elastic search:
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
        - name: vm.max_map_count
          value: 262144
    - name: install system dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - tmux
        - fish
        # NOTE (jpd): needed by asdf to list java plugins
        - jq
        # NOTE (jpd): needed by tmux plugins
        - gawk
        - xsel
    - name: set shell for user
      user:
        name: '{{ ansible_user }}'
        shell: /usr/bin/fish
  roles:
    - geerlingguy.docker
    # NOTE (jpd): not sure if this role is needed here
    - geerlingguy.pip
