---
# TODO (jpd): geerlingguy.pip requires sudo to be enabled
- hosts: dev
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: tmuxp
  tasks:
    - name: install tmux plugins
      git:
        repo: 'https://github.com/tmux-plugins/tpm.git'
        dest: '{{ ansible_env.HOME }}/.tmux/plugins/tpm'
  roles:
    - geerlingguy.pip
