---
services:
  git:
    image: "gitea/gitea:1.25.5"
    init: true
    hostname: git
    environment:
      APP_NAME: ${GIT_APP_NAME:-gitea}
      USER_UID: ${UID:-1000}
      USER_GID: ${GID:-1000}
      RUN_MODE: ${GIT_RUN_MODE:-prod}
      DOMAIN: ${GIT_DOMAIN:-localhost}
      SSH_DOMAIN: ${GIT_SSH_DOMAIN:-localhost}
      HTTP_PORT: ${GIT_HTTP_PORT:-3000}
      ROOT_URL: http://${GIT_DOMAIN:-localhost}:3000
      SSH_PORT: ${GIT_SSH_PORT:-222}
      SSH_LISTEN_PORT: ${GIT_SSH_LISTEN_PORT:-22}
      DB_TYPE: ${GIT_DB_TYPE:-sqlite3}
      DISABLE_REGISTRATION: ${GIT_DISABLE_REGISTRATION:-true}
    restart: unless-stopped
    volumes:
      - "git_data:/data"
    networks:
      - git_cicd_net
    ports:
      - "222:22"
  cron:
    image: "premoweb/chadburn:1.0.7"
    init: true
    hostname: cron
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/cron:/opt/chadburn"
    restart: unless-stopped
    networks:
      - git_cicd_net
    command: daemon --config=/opt/chadburn/config.ini
  # TODO (jpd): to start renovate we must change ownership of renovate_data to
  # ubuntu user
  renovate:
    image: "renovate/renovate:43.102.11-full"
    init: true
    hostname: renovate
    environment:
      GITHUB_COM_TOKEN: ${GITHUB_COM_TOKEN:-token}
      RENOVATE_TOKEN: ${RENOVATE_TOKEN:-token}
      RENOVATE_GIT_AUTHOR: ${RENOVATE_GIT_AUTHOR:-'renovate <renovate@example.com>'}
      RENOVATE_CONFIG_FILE: "/opt/renovate/config.js"
      RENOVATE_BASE_DIR: "/opt/renovate_data"
    labels:
      chadburn.enabled: "true"
      chadburn.job-exec.renovate.schedule: "@every 30m"
      chadburn.job-exec.renovate.command: "/usr/local/sbin/renovate"
    volumes:
      - "./config/renovate:/opt/renovate"
      - "renovate_data:/opt/renovate_data"
    restart: unless-stopped
    networks:
      - git_cicd_net
    entrypoint: sleep
    command: infinity
  minio:
    image: "quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z"
    hostname: minio
    environment:
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL:-http://localhost}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-dubas}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-dubas}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-http://localhost}
      MINIO_VOLUMES: /snsd_data
    volumes:
      - "minio_data:/data"
      - "minio_snsd_data:/snsd_data"
    restart: unless-stopped
    networks:
      - git_cicd_net
    command: 'server --console-address ":9001"'
  mc:
    image: "quay.io/minio/mc:RELEASE.2025-02-21T16-00-46Z"

volumes:
  git_data: {}
  ci_data: {}
  renovate_data: {}
  minio_data: {}
  minio_snsd_data: {}

networks:
  git_cicd_net:
    name: git_cicd_net
