---
version: '3.7'

services:
  zsh:
    image: 'joaodubas/zsh:dev'
    build: .
    init: true
    volumes:
      - './config/zsh:/home/me/.config/zsh'
    hostname: zsh
    entrypoint: sleep
    command: infinity
