[tools]
awscli = "2.15.6"
bat = "0.24.0"
dagger = "0.9.5"
elixir = "1.16.0-otp-26"
erlang = "26.2.1"
eza = "0.17.0"
fzf = "0.45.0"
go = "1.21.5"
helm = "3.13.3"
k3d = "5.6.0"
kubectl = "1.29.0"
kubie = "0.23.0"
lefthook = "1.5.5"
node = "21.5.0"
poetry = "1.7.1"
python = "3.12.1"
ripgrep = "14.1.0"
starship = "1.17.1"
terraform = "1.6.6"
tilt = "0.33.10"
tmux = "3.3"
usql = "0.17.2"
yarn = "1.22.19"
zoxide = "0.9.2"

[settings]
experimental = true
