FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y python3 python3-setuptools python3-pip \
    && pip3 install --upgrade pip

ENV HOME_APP /opt/app
ENV FLASK_APP ${HOME_APP}/app.py
COPY ./src ${HOME_APP}
RUN pip install -r /opt/app/requirements.txt
