FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y curl gpg
RUN curl https://packages.microsoft.com/keys/microsoft.asc \
        | gpg --dearmor > microsoft.gpg
RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" \
        > /etc/apt/sources.list.d/vscode.list
RUN apt-get update \
    && apt-get install -y code
