---
services:
  server:
    build:
      context: 'https://github.com/OpenSignLabs/OpenSign.git#${OS_GIT_REF:-v1.8.1}:apps/OpenSignServer'
    image: 'joaodubas/opensignserver:${OS_GIT_REF:-v1.8.1}'
    init: true
    restart: unless-stopped
    hostname: opensign_server
    depends_on:
      - db
    environment:
      APP_ID: &app_id ${OS_APP_ID:-arandomnames}
      appName: dubas_signer
      MASTER_KEY: arandommaink
      MONGODB_URI: 'mongodb://db:27017'
      PARSE_MOUNT: /app
      SERVER_URL: &server_url '${OS_SERVER_URL:-https://api.opensign.dubas.dev/app}'
      DO_SPACE: 'opensign'
      DO_BASEURL: 'http://s3:9090/opensign'
      DO_ENDPOINT: 's3:9090'
      DO_ACCESS_KEY_ID: 'eE4Bq5h75QsAb2tzoXPd'
      DO_SECRET_ACCESS_KEY: 'gBaIvqmvPyqoNgw2RBIy6FQOQBoO4QT99h329IZR'
      DO_REGION: us-east-1
    entrypoint: /usr/src/app/node_modules/.bin/nodemon
    command: server.js
  client:
    build:
      context: 'https://github.com/OpenSignLabs/OpenSign.git#${OS_GIT_REF:-v1.8.1}:apps/OpenSign'
    image: 'joaodubas/opensignclient:${OS_GIT_REF:-v1.8.1}'
    init: true
    restart: unless-stopped
    hostname: opensign_client
    depends_on:
      - server
    environment:
      CI: 'false'
      PUBLIC_URL: '${OS_CLIENT_URL:-https://opensign.dubas.dev}'
      GENERATE_SOURCEMAP: 'false'
      REACT_APP_SERVERURL: *server_url
      REACT_APP_ID: *app_id
      REACT_APP_GTM: 
    entrypoint: npm
    command: start
  db:
    image: 'mongo:7.0.2-jammy'
    init: true
    restart: unless-stopped
    hostname: mongodb
    volumes:
      - 'db_data:/data/db'
  s3:
    image: 'quay.io/minio/minio:RELEASE.2024-06-29T01-20-47Z'
    environment:
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL:-http://localhost:9001}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-3atbJUTYTWHBeY5qQA2iw3KJaqVsTQBK}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-dubas}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-http://localhost:9000}
      MINIO_VOLUMES: /snsd_data
    volumes:
      - 'minio_snsd_data:/snsd_data'
    restart: unless-stopped
    command: 'server --console-address ":9001"'
volumes:
  db_data: {}
  minio_snsd_data: {}
