---
services:
  server:
    build:
      context: 'https://github.com/OpenSignLabs/OpenSign.git#${OS_GIT_REF:-v1.8.1}:apps/OpenSignServer'
    image: 'joaodubas/opensignserver:${OS_GIT_REF:-v1.8.1}'
    init: true
    restart: unless-stopped
    hostname: opensign_server
    depends_on:
      - db
    environment:
      APP_ID: arandomnames
      appName: dubas_signer
      MASTER_KEY: arandommaink
      MONGODB_URI: 'mongodb://db:27017'
      PARSE_MOUNT: /app
      SERVER_URL: 'https://api.opensign.dubas.dev/api/app'
    entrypoint: /usr/src/app/node_modules/.bin/nodemon
    command: server.js
  client:
    build:
      context: 'https://github.com/OpenSignLabs/OpenSign.git#${OS_GIT_REF:-v1.8.1}:apps/OpenSign'
    image: 'joaodubas/opensignclient:${OS_GIT_REF:-v1.8.1}'
    init: true
    restart: unless-stopped
    hostname: opensign_client
    depends_on:
      - server
    environment:
      CI: 'false'
      PUBLIC_URL: 'https://opensign.dubas.dev'
      GENERATE_SOURCEMAP: 'false'
      REACT_APP_SERVERURL: 'https://api.opensign.dubas.dev/api/app'
      REACT_APP_ID: arandomnames
      REACT_APP_GTM: 
    entrypoint: npm
    command: start
  db:
    image: 'mongo:7.0.2-jammy'
    init: true
    restart: unless-stopped
    hostname: mongodb
    volumes:
      - 'db-data:/data/db'
volumes:
  db-data: {}
