---
auth: password
cert: false
disable-telemetry: true
disable-update-check: true
bind-addr: '0.0.0.0:8443'
user-data-dir: '/home/coder/project'
extensions-dir: '/home/coder/.cache/code-server'
verbose: true
