---
version: '2.3'
services:
  dind:
    image: 'local/docker:18.04.0-ce-dind'
    build: ./
    privileged: true
    hostname: dind
    volumes:
      - 'lib_docker:/var/lib/docker'
volumes:
  lib_docker: