---
services:
  streams:
    image: 'redis:7.2.4-bookworm'
    init: true
    hostname: &redis_hostname streams
    restart: unless-stopped
    environment:
      TERM: xterm-color
    volumes:
      - 'redis_data:/data'
    command: redis-server --protected-mode no
  dragonfly-streams:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly:v1.15.1'
    init: true
    hostname: &dragonfly_hostname dragonfly-streams
    restart: unless-stopped
    volumes:
      - 'dragonfly_data:/data'
  key-streams:
    image: 'eqalpha/keydb:alpine_x86_64_v6.3.4'
    hostname: &key_hostname key-streams
    restart: unless-stopped
    volumes:
      - 'key_data:/data'
  producer:
    image: &golang_image 'golang:1.22.1'
    init: true
    restart: unless-stopped
    depends_on: &producer_service_dependencies
      - streams
      - dragonfly-streams
      - key-streams
    environment: &stream_configuration
      STREAM_HOST: *redis_hostname
      STREAM_PORT: 6379
    volumes:
      - './producer:/go/src/app'
    working_dir: /go/src/app
    command: go run main.go
  producer-py:
    image: 'joaodubas/producer-py:3.12'
    build:
      args: &python_args
        POETRY_VERSION: 1.8.2
      context: ./producer-py
    init: true
    restart: unless-stopped
    depends_on: *producer_service_dependencies
    environment:
      <<: *stream_configuration
    volumes:
      - './producer-py:/usr/local/src/app'
    command: python producer.py
  consumer:
    image: *golang_image
    init: true
    restart: unless-stopped
    depends_on: &consumer_service_dependencies
      - producer
      - producer-py
    environment:
      <<: *stream_configuration
    volumes:
      - './consumer:/go/src/app'
    working_dir: /go/src/app
    command: go run main.go
  consumer-py:
    image: 'joaodubas/consumer-py:3.12'
    build:
      args: *python_args
      context: ./consumer-py
    init: true
    restart: unless-stopped
    depends_on: *consumer_service_dependencies
    environment:
      <<: *stream_configuration
    volumes:
      - './consumer-py:/usr/local/src/app'
    command: python consumer.py
volumes:
  dragonfly_data: {}
  key_data: {}
  redis_data: {}
