---
version: '3'
services:
  streams:
    image: joaodubas/redis:5.0-rc3
    environment:
      TERM: xterm-color
  producer:
    image: golang:1.10
    volumes:
      - './producer:/go/src/app'
    working_dir: /go/src/app
    command: go run main.go
  consumer:
    image: golang:1.10
    volumes:
      - './consumer:/go/src/app'
    working_dir: /go/src/app
    command: go run main.go
